CREATE TABLE  "TB_STATUS" 
   (    "ID_STATUS" NUMBER(*,0) NOT NULL ENABLE, 
    "METHOD" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
     CONSTRAINT "TB_STATUS_PK" PRIMARY KEY ("ID_STATUS") ENABLE
   ) ;CREATE TABLE  "TB_USER" 
   (    "ID_USER" NUMBER(*,0) NOT NULL ENABLE, 
    "NAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
    "DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
    "ADDRESS" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
    "REGIS_DATE" DATE NOT NULL ENABLE, 
    "TB_ROLE_ID_ROLE" NUMBER(*,0) NOT NULL ENABLE, 
    "NO_HANDPHONE" NUMBER(*,0) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(255) NOT NULL ENABLE, 
     CONSTRAINT "TB_USER_PK" PRIMARY KEY ("ID_USER") ENABLE
   ) ;CREATE TABLE  "TB_MENTORSHIP" 
   (    "ID_MENTORSHIP" NUMBER(*,0) NOT NULL ENABLE, 
    "SPECIALIZATION" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
    "AVAILABILITY" VARCHAR2(200), 
    "RATE" NUMBER, 
    "DESCRIPTION" VARCHAR2(150 CHAR) NOT NULL ENABLE, 
    "PRICE" NUMBER(*,0) NOT NULL ENABLE, 
    "TB_STATUS_ID_STATUS" NUMBER(*,0) NOT NULL ENABLE, 
    "TB_USER_ID_USER" NUMBER, 
    "IMG" VARCHAR2(255), 
     CONSTRAINT "TB_MENTORSHIP_PK" PRIMARY KEY ("ID_MENTORSHIP") ENABLE
   ) ;CREATE TABLE  "TB_SESSION" 
   (    "ID_SESSION" NUMBER(*,0) NOT NULL ENABLE, 
    "TIME_START" DATE NOT NULL ENABLE, 
    "TIME_END" DATE NOT NULL ENABLE, 
    "TB_REVIEW_ID_REVIEW" NUMBER(*,0) NOT NULL ENABLE, 
    "TB_PAYMENT_ID_PAYMENT" NUMBER(*,0) NOT NULL ENABLE, 
    "TB_USER_ID_USER" NUMBER(*,0) NOT NULL ENABLE, 
    "TB_MENTORSHIP_ID_MENTORSHIP" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "TB_SESSION_PK" PRIMARY KEY ("ID_SESSION") ENABLE
   ) ;CREATE TABLE  "TB_PAYMENT" 
   (    "ID_PAYMENT" NUMBER(*,0) NOT NULL ENABLE, 
    "AMOUNT" NUMBER(*,0) NOT NULL ENABLE, 
    "date" DATE NOT NULL ENABLE, 
    "METHOD" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
    "TB_SESSION_ID_SESSION" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "TB_PAYMENT_PK" PRIMARY KEY ("ID_PAYMENT") ENABLE
   ) ;CREATE TABLE  "TB_REVIEW" 
   (    "ID_REVIEW" NUMBER(*,0) NOT NULL ENABLE, 
    "RATING" NUMBER(*,0) NOT NULL ENABLE, 
    "comment" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
    "date" DATE NOT NULL ENABLE, 
    "TB_SESSION_ID_SESSION" NUMBER(*,0) NOT NULL ENABLE, 
    "TB_USER_ID_USER" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "TB_REVIEW_PK" PRIMARY KEY ("ID_REVIEW") ENABLE
   ) ;CREATE TABLE  "TB_ROLE" 
   (    "ID_ROLE" NUMBER(*,0) NOT NULL ENABLE, 
    "NAMEROLE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
     CONSTRAINT "TB_ROLE_PK" PRIMARY KEY ("ID_ROLE") ENABLE
   ) ;ALTER TABLE  "TB_MENTORSHIP" ADD CONSTRAINT "TB_MENTORSHIP_TB_STATUS_FK" FOREIGN KEY ("TB_STATUS_ID_STATUS")
      REFERENCES  "TB_STATUS" ("ID_STATUS") ENABLE;ALTER TABLE  "TB_MENTORSHIP" ADD CONSTRAINT "TB_MENTORSHIP_TB_USER_FK" FOREIGN KEY ("TB_USER_ID_USER")
      REFERENCES  "TB_USER" ("ID_USER") ENABLE;ALTER TABLE  "TB_PAYMENT" ADD CONSTRAINT "TB_PAYMENT_TB_SESSION_FK" FOREIGN KEY ("TB_SESSION_ID_SESSION")
      REFERENCES  "TB_SESSION" ("ID_SESSION") ENABLE;ALTER TABLE  "TB_REVIEW" ADD CONSTRAINT "TB_REVIEW_TB_SESSION_FK" FOREIGN KEY ("TB_SESSION_ID_SESSION")
      REFERENCES  "TB_SESSION" ("ID_SESSION") ENABLE;ALTER TABLE  "TB_REVIEW" ADD CONSTRAINT "TB_REVIEW_TB_USER_FK" FOREIGN KEY ("TB_USER_ID_USER")
      REFERENCES  "TB_USER" ("ID_USER") ENABLE;ALTER TABLE  "TB_SESSION" ADD CONSTRAINT "TB_SESSION_TB_MENTORSHIP_FK" FOREIGN KEY ("TB_MENTORSHIP_ID_MENTORSHIP")
      REFERENCES  "TB_MENTORSHIP" ("ID_MENTORSHIP") ENABLE;ALTER TABLE  "TB_SESSION" ADD CONSTRAINT "TB_SESSION_TB_PAYMENT_FK" FOREIGN KEY ("TB_PAYMENT_ID_PAYMENT")
      REFERENCES  "TB_PAYMENT" ("ID_PAYMENT") ENABLE;ALTER TABLE  "TB_SESSION" ADD CONSTRAINT "TB_SESSION_TB_REVIEW_FK" FOREIGN KEY ("TB_REVIEW_ID_REVIEW")
      REFERENCES  "TB_REVIEW" ("ID_REVIEW") ENABLE;ALTER TABLE  "TB_SESSION" ADD CONSTRAINT "TB_SESSION_TB_USER_FK" FOREIGN KEY ("TB_USER_ID_USER")
      REFERENCES  "TB_USER" ("ID_USER") ENABLE;ALTER TABLE  "TB_USER" ADD CONSTRAINT "TB_USER_TB_ROLE_FK" FOREIGN KEY ("TB_ROLE_ID_ROLE")
      REFERENCES  "TB_ROLE" ("ID_ROLE") ENABLE;

      